name: office-reservation-system

services:
  reservation-service:
    build:
      context: ./application/reservation-service
      dockerfile: Dockerfile
    container_name: reservation-service
    ports:
      - "8000:8000"
    restart: unless-stopped

  user-notification-service:
    build:
      context: ./application/user-notification-service
      dockerfile: Dockerfile
    container_name: user-notification-service
    ports:
      - "8001:8001"
    restart: unless-stopped

  frontend:
    build:
      context: ./application/frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - reservation-service
      - user-notification-service
    restart: unless-stopped
