apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-storageclass.yaml
  - postgres-secret.yaml
  - postgres-statefulset.yaml
  - reservation-service.yaml
  - user-notification-service.yaml
  - frontend.yaml
  - hpa-reservation-service.yaml
